
default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: root
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: theam_saloon_development


test:
  <<: *default
  database: theam_saloon_test


production:
  <<: *default
  database: theam_saloon_production
  username: theam_saloon
  password: <%= ENV['THEAM_SALOON_DATABASE_PASSWORD'] %>
