
default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: root
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: final_saloons_development


test:
  <<: *default
  database: final_saloons_test


production:
  <<: *default
  database: final_saloons_production
  username: final_saloons
  password: <%= ENV['FINAL_SALOONS_DATABASE_PASSWORD'] %>
