
default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: Root123!
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: beauty_development


test:
  <<: *default
  database: beauty_test

production:
  <<: *default
  database: beauty_production
  username: beauty
  password: <%= ENV['BEAUTY_DATABASE_PASSWORD'] %>
