default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: root
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: salon_development


test:
  <<: *default
  database: salon_test

production:
  <<: *default
  database: salon_production
  username: salon
  password: <%= ENV['SALON_DATABASE_PASSWORD'] %>
