
default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: root
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: final_saloon_development


test:
  <<: *default
  database: final_saloon_test

production:
  <<: *default
  database: final_saloon_production
  username: final_saloon
  password: <%= ENV['FINAL_SALOON_DATABASE_PASSWORD'] %>
