
default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: root
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: demo_development


test:
  <<: *default
  database: demo_test

production:
  <<: *default
  database: demo_production
  username: demo
  password: <%= ENV['DEMO_DATABASE_PASSWORD'] %>
