
default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: root
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: SALOON_development

test:
  <<: *default
  database: SALOON_test

production:
  <<: *default
  database: SALOON_production
  username: SALOON
  password: <%= ENV['SALOON_DATABASE_PASSWORD'] %>
