default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: root
  host: localhost
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: saloon_development

test:
  <<: *default
  database: saloon_test

production:
  <<: *default
  database: <%= ENV['SALOON_DATABASE_DBNAME'] %>
  username: <%= ENV['SALOON_DATABASE_USERNAME'] %>
  password: <%= ENV['SALOON_DATABASE_PASSWORD'] %>
